### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 17cupsofcoffee** [17cupsofcoffee/mona#1]
This is an ongoing checklist of the work that needs to be done before a public test release. Stuff will probably get added/be missing at first!

- [ ] **Overall Goals**
  - [ ] Data persistence
  - [ ] Create a website for the app

- [ ] **Dashboard**
  - [ ] Find a way of pulling the data from each individual page - might require moving the app state into the top level component and passing it where needed through props

- [ ] **Project Manager**
  - [ ] Implement the UI using a static set of data for testing

- [ ] **Budget Panel**
  - [ ] Implement the UI using a static set of data for testing
  - [ ] Integrate into the other tools (when a project is paid for, add the income to the tracker, etc)
  - [ ] Allow for integration with other services if possible (Patreon?)

- [ ] **Options/Customization**
  - [ ] Templates for projects
  - [ ] Editable templates for the email notifications (perhaps using Markdown or something like that)
  - [ ] Make the payment schemes customizable (some people get commission money up front, some people get half before and half after - probably allow to set percentages)

- [ ] **Email Notifications**
  - [ ] Hook into the Mailgun API (or something similar), to save us having to run our own email server.
  - [ ] Provide options for customizing when the emails get sent and what text is in them
  - [ ] Make sure there's some kind of rate limiting so people can't use the app to spam people

- [ ] **Testing**
  - [x] Set up a Mocha/Karma testing environment
  - [ ] Create a good suite of tests for the existing components
